-- Generated by wallust. Do not edit.
return {
   bg          = "{{background}}",
   surface     = "{{background | lighten(0.08)}}",
   surface_alt = "{{background | lighten(0.12)}}",
   fg          = "{{foreground}}",
   fg_alt      = "{{foreground | darken(0.25)}}",
   fg_muted    = "{{color8}}",
   border      = "{{background | lighten(0.08)}}",
   accent      = "{{color12}}",
   accent_alt  = "{{color9}}",
   success     = "{{color2}}",
   warning     = "{{color13}}",
   error       = "{{color1}}",
   info        = "{{color5}}",
   highlight   = "{{background | lighten(0.12)}}",
}
