# Generated by wallust. Do not edit.
export WALLUST_ZSH_USER_FG="{{color12}}"
export WALLUST_ZSH_HOST_FG="{{color14}}"
export WALLUST_ZSH_PATH_FG="{{color6}}"
export WALLUST_ZSH_PROMPT_FG="{{foreground}}"
export WALLUST_ZSH_RPROMPT_FG="{{color8}}"
